[package]
name = "pysyntect"
version = "0.1.0"
authors = ["Edgar Andrés Margffoy Tuay <andfoy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "syntect"
crate-type = ["cdylib"]

[dependencies]
syntect = "3.3"

[dependencies.pyo3]
version = "0.9.0"
features = ["extension-module"]
